version: '3.6'

services:
  home:
    image: nginx:alpine
    restart: always
    ports:
      - 80
    volumes:
      - ./dist:/usr/share/nginx/html:ro
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.docker.network=traefik
      - traefik.backend=rauchmelder
      - traefik.frontend.rule=Host:rauchmelder.nicco.io

networks:
  traefik:
    external: true